// ============================================================
// VAULT v3 — Complete Portfolio Dashboard
// ============================================================
const SHEET_ID='18VynzaZPeJTbdn4Hwxeslre1A8_H7_zdBQu9OWd7E_8';
const PUB_ID='2PACX-1vQHtSe6vE3WSfSsoW15kEaKv75UYpRGM0QJ26_MJlys7ML1NPid2b_Ys6jII04owAH9v4NfOelpVsAm';
const SB_URLS=[`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=Neverless`,`https://docs.google.com/spreadsheets/d/e/${PUB_ID}/pub?output=csv&gid=0`,`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=Feuille%201`];
const RC_URLS=[`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=Revolut_Crypto`];
const RR_URLS=[`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=Revolut_Robo`];
const CG='https://api.coingecko.com/api/v3';
const GAS='https://script.google.com/macros/s/AKfycbwJbGQ9SqkQQ5nVhGU_vW5oDWbtb0uEJpaQVf0TtUy0gRRLBdSrJmymlRBhls7O4rot/exec';
const CGM={BTC:'bitcoin',ETH:'ethereum',SOL:'solana',XRP:'ripple',ADA:'cardano',DOGE:'dogecoin',AVAX:'avalanche-2',LINK:'chainlink',UNI:'uniswap',AAVE:'aave',COMP:'compound-governance-token',RENDER:'render-token',FET:'artificial-superintelligence-alliance',ARB:'arbitrum',OP:'optimism',POL:'polygon-ecosystem-token',HBAR:'hedera-hashgraph',ALGO:'algorand',SUI:'sui',TAO:'bittensor',PEPE:'pepe',BONK:'bonk',FLOKI:'floki',NOT:'notcoin',JUP:'jupiter-exchange-solana',PYTH:'pyth-network',S:'sonic-svm',W:'wormhole',USDC:'usd-coin',USDT:'tether',EURC:'euro-coin',MOODENG:'moo-deng',ACT:'act-i-the-ai-prophecy',POPCAT:'popcat',L3:'layer3',DEGEN:'degen-base',GRASS:'grass',ENA:'ethena',ANKR:'ankr',CKB:'nervos-network',RSR:'reserve-rights-token',TURBO:'turbo',NMR:'numeraire',TON:'the-open-network',CFX:'conflux-token',MNT:'mantle',CORE:'coredaoorg',JASMY:'jasmycoin',WLD:'worldcoin-wld',VIRTUAL:'virtuals-protocol',AIOZ:'aioz-network',PENDLE:'pendle',LTC:'litecoin',BCH:'bitcoin-cash',CAKE:'pancakeswap-token',XAU:'pax-gold',BABYDOGE:'baby-doge-coin',VET:'vechain',AERO:'aerodrome-finance',PI:'pi-network',AR:'arweave',ATOM:'cosmos',MEW:'cat-in-a-dogs-world',DOT:'polkadot',SEI:'sei-network',CRO:'crypto-com-chain',ZKJ:'polyhedra-network',CTXC:'cortex',MOG:'mog-coin',SAMO:'samoyedcoin',STEEM:'steem',API3:'api3'};
const ETFY={WELK:'WELK.DE',XDWI:'XDWI.DE',EBUY:'EBUY.DE',AMEL:'AMEL.DE',LYMS:'LYMS.DE',LEMA:'LEMA.DE',PRAJ:'PRAJ.DE',LGQK:'LGQK.DE',LYP5:'LYP5.DE',LYP6:'LYP6.F','79U0':'MUSA.PA',XDWT:'XDWT.DE',EXW1:'EXW1.DE',EXI2:'EXI2.DE',XUCD:'XUCD.DE',IS3Q:'IS3Q.DE',IS3K:'IS3K.DE',AMEM:'AMEM.DE',DBXJ:'DBXJ.DE'};
const ETFN={'2B72':'Amundi MSCI EM II',WELK:'Amundi MSCI World Climate',EBUY:'Amundi MSCI World Ex-EU',AMEL:'Amundi MSCI EM III',LYMS:'Amundi MSCI EM Asia',LEMA:'Amundi MSCI EM LatAm',XDWI:'Xtrackers MSCI World IT',PRAJ:'Amundi Prime Japan','79U0':'Amundi MSCI USA',LYP5:'Amundi MSCI World',UBUD:'UBS MSCI Japan SF',LYP6:'Amundi Stoxx Europe 600',LGQK:'L&G Quality Eq Div',EXW1:'iShares EURO STOXX 50',EXI2:'iShares DJ Global Titans',XUCD:'Xtrackers MSCI USA Cons',IS3Q:'iShares MSCI World Quality',IS3K:'iShares HY Corp Bond',XDWT:'Xtrackers MSCI World',AMEM:'Amundi MSCI EM',DBXJ:'Xtrackers MSCI Japan'};

let sbTx=[],rcTx=[],rrTx=[];
let cryptoH={},etfH={};
let prices={},etfP={},mktData=[],pHistory=[],fgData=null;
let selPeriod=7,curSort={col:'value',dir:'desc'},eurUsd=1.16;

// CSV
function parseCSV(t){const ls=t.split('\n');if(ls.length<2)return[];const h=csvL(ls[0]);const r=[];for(let i=1;i<ls.length;i++){if(!ls[i].trim())continue;const v=csvL(ls[i]);const o={};h.forEach((k,j)=>{o[k.trim()]=(v[j]||'').trim();});r.push(o);}return r;}
function csvL(l){const r=[];let c='',q=false;for(let i=0;i<l.length;i++){const ch=l[i];if(ch==='"')q=!q;else if(ch===','&&!q){r.push(c);c='';}else c+=ch;}r.push(c);return r;}
function pn(s){if(!s)return 0;s=s.trim().replace(/["\xa0€$ ]/g,'');if(/[eE][+-]/.test(s))return parseFloat(s.replace(',','.'))||0;if(s.includes(',')&&!s.includes('.'))s=s.replace(',','.');return parseFloat(s)||0;}
async function getCSV(urls,lbl){for(const u of urls){try{const r=await fetch(u);if(!r.ok)continue;const t=await r.text();if(t.length>30&&!t.includes('<!DOCTYPE')){console.log('✓',lbl);return t;}}catch(e){}}console.warn('✗',lbl);return null;}

// Holdings
function compSB(tx){const b={},F=new Set(['EUR','USD']);tx.forEach(t=>{const ra=pn(t['Amount received']),rs=t['Asset received']||'';const sa=pn(t['Amount sent']),ss=t['Asset sent']||'';const fa=pn(t['Fee']),fs=t['Asset of the fee']||'';if(ra&&rs&&!F.has(rs))b[rs]=(b[rs]||0)+ra;if(sa&&ss&&!F.has(ss))b[ss]=(b[ss]||0)-sa;if(fa&&fs&&!F.has(fs))b[fs]=(b[fs]||0)-fa;});return b;}
function compRC(tx){const b={};tx.forEach(t=>{const s=(t.Symbol||'').trim(),tp=(t.Type||'').trim(),q=pn(t.Quantity);if(!s||!q)return;if(tp==='Achat'||tp.includes('compense'))b[s]=(b[s]||0)+q;else if(tp==='Vente'||tp==='Envoi')b[s]=(b[s]||0)-q;});return b;}
function compRR(tx){const b={};tx.forEach(t=>{const tk=(t.Ticker||'').trim(),tp=(t.Type||'').trim(),q=pn(t.Quantity);if(!tk||!q)return;if(tp.includes('BUY'))b[tk]=(b[tk]||0)+q;else if(tp.includes('SELL'))b[tk]=(b[tk]||0)-q;});return b;}
function merge(){cryptoH={};const sb=compSB(sbTx),rc=compRC(rcTx);for(const[s,q]of Object.entries(sb))cryptoH[s]=(cryptoH[s]||0)+q;for(const[s,q]of Object.entries(rc))cryptoH[s]=(cryptoH[s]||0)+q;for(const s of Object.keys(cryptoH))if(Math.abs(cryptoH[s])<1e-7)delete cryptoH[s];etfH={};const rr=compRR(rrTx);for(const[t,q]of Object.entries(rr))if(q>0.0001)etfH[t]=q;}
function getSrc(s){const a=(compSB(sbTx)[s]||0)>1e-7,b=(compRC(rcTx)[s]||0)>1e-7;if(a&&b)return'Multi';if(b)return'Revolut';return'SwissBorg';}

// Prices
async function fetchEurUsd(){try{const r=await fetch(`${CG}/simple/price?ids=tether&vs_currencies=eur`);if(r.ok){const d=await r.json();if(d.tether?.eur)eurUsd=1/d.tether.eur;}}catch(e){}console.log('EUR/USD:',eurUsd.toFixed(3));}
async function fetchPrices(a){const ids=[],m={};a.forEach(s=>{const id=CGM[s];if(id){ids.push(id);m[id]=s;}});if(!ids.length)return{};const pd={};for(let i=0;i<ids.length;i+=50){try{const r=await fetch(`${CG}/coins/markets?vs_currency=usd&ids=${ids.slice(i,i+50).join(',')}&order=market_cap_desc&sparkline=false&price_change_percentage=24h,7d,30d,1y`);if(r.ok)(await r.json()).forEach(c=>{const s=m[c.id];if(s)pd[s]={price:c.current_price||0,ch24:c.price_change_percentage_24h||0,ch7d:c.price_change_percentage_7d_in_currency||0,ch30d:c.price_change_percentage_30d_in_currency||0,ch1y:c.price_change_percentage_1y_in_currency||0,mcap:c.market_cap||0,img:c.image||'',name:c.name||s,rank:c.market_cap_rank||999,ath:c.ath||0,athDate:c.ath_date||''};});if(i+50<ids.length)await sleep(1500);}catch(e){}}return pd;}
async function fetchETF(){etfP={};const lp={};rrTx.forEach(t=>{const tk=(t.Ticker||'').trim(),p=pn((t['Price per share']||'').replace('EUR',''));if(tk&&p>0)lp[tk]=p;});for(const tk of Object.keys(etfH)){const y=ETFY[tk];if(y){try{const ctrl=new AbortController();const tmr=setTimeout(()=>ctrl.abort(),4000);const r=await fetch(`https://api.allorigins.win/raw?url=${encodeURIComponent(`https://query1.finance.yahoo.com/v8/finance/chart/${y}?interval=1d&range=5d`)}`,{signal:ctrl.signal});clearTimeout(tmr);if(r.ok){const d=await r.json();const p=d?.chart?.result?.[0]?.meta?.regularMarketPrice;if(p){etfP[tk]={eur:p,name:ETFN[tk]||tk};continue;}}}catch(e){console.warn('ETF fetch fail:',tk,e.message);}}etfP[tk]={eur:lp[tk]||0,name:ETFN[tk]||tk};}}
async function fetchMkt(){try{const r=await fetch(`${CG}/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=1&sparkline=false&price_change_percentage=24h,7d,30d,1y`);if(!r.ok)return[];const d=await r.json();const has=new Set(d.map(c=>c.id));const extra=[...new Set(Object.keys(cryptoH).filter(s=>cryptoH[s]>1e-7).map(s=>CGM[s]).filter(id=>id&&!has.has(id)))];if(!has.has('grass'))extra.push('grass');if(extra.length){await sleep(1200);try{const r2=await fetch(`${CG}/coins/markets?vs_currency=usd&ids=${extra.join(',')}&sparkline=false&price_change_percentage=24h,7d,30d,1y`);if(r2.ok)d.push(...await r2.json());}catch(e){}}return d;}catch(e){return[];}}
async function fetchFG(){try{const r=await fetch('https://api.alternative.me/fng/?limit=1');if(r.ok){const d=await r.json();if(d.data?.[0])fgData={value:parseInt(d.data[0].value),label:d.data[0].value_classification};}}catch(e){}}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}

// Items
function allItems(){const it=[];for(const[s,q]of Object.entries(cryptoH)){if(q<=1e-7)continue;const p=prices[s]||{};it.push({sym:s,qty:q,priceUSD:p.price||0,valUSD:q*(p.price||0),ch24:p.ch24||0,ch7d:p.ch7d||0,ch30d:p.ch30d||0,ch1y:p.ch1y||0,img:p.img||'',name:p.name||s,type:'crypto',src:getSrc(s)});}for(const[tk,q]of Object.entries(etfH)){const e=etfP[tk]||{};const pe=e.eur||0;it.push({sym:tk,qty:q,priceUSD:pe*eurUsd,priceEUR:pe,valUSD:q*pe*eurUsd,valEUR:q*pe,ch24:0,ch7d:0,ch30d:0,ch1y:0,img:'',name:e.name||ETFN[tk]||tk,type:'etf',src:'Robo-Advisor'});}return it;}

// Render Holdings
function renderH(){const tb=document.getElementById('holdingsBody');let it=allItems().filter(i=>i.valUSD>=10);it.sort((a,b)=>{let va,vb;switch(curSort.col){case'name':return curSort.dir==='asc'?a.sym.localeCompare(b.sym):b.sym.localeCompare(a.sym);case'qty':va=a.qty;vb=b.qty;break;case'price':va=a.priceUSD;vb=b.priceUSD;break;case'value':va=a.valUSD;vb=b.valUSD;break;case'change24h':va=a.ch24;vb=b.ch24;break;case'change7d':va=a.ch7d;vb=b.ch7d;break;case'change30d':va=a.ch30d;vb=b.ch30d;break;case'change1y':va=a.ch1y;vb=b.ch1y;break;default:va=a.valUSD;vb=b.valUSD;}return curSort.dir==='asc'?va-vb:vb-va;});const tot=it.reduce((s,i)=>s+i.valUSD,0);if(!it.length){tb.innerHTML='<tr><td colspan="9" class="loading-cell">Aucune position ≥ 10$</td></tr>';return;}
function fc(v,e){if(e)return'<td class="change-na">—</td>';const c=v>=0?'change-positive':'change-negative';return`<td class="${c}">${v>=0?'+':''}${v.toFixed(2)}%</td>`;}
function st(s){const c={SwissBorg:'#06d6a0',Revolut:'#0075eb',Multi:'#8b5cf6','Robo-Advisor':'#ea580c'}[s]||'#94a3b8';return`<span style="font-size:0.58rem;font-family:var(--font-mono);background:${c}15;color:${c};padding:0.1rem 0.35rem;border-radius:3px;margin-left:0.3rem">${s}</span>`;}
tb.innerHTML=it.map(i=>{const al=tot>0?(i.valUSD/tot*100):0;const e=i.type==='etf';const pd=e?`€${i.priceEUR.toFixed(2)}`:fU(i.priceUSD);return`<tr><td><div class="asset-cell"><div class="asset-icon"${e?' style="background:#ea580c15;color:#ea580c;border-color:#ea580c30"':''}>${i.img?`<img src="${i.img}" alt="${i.sym}" onerror="this.parentElement.textContent='${i.sym.slice(0,2)}'">`:i.sym.slice(0,2)}</div><div><div class="asset-name">${e?i.sym:i.name} ${st(i.src)}</div><div class="asset-symbol">${e?i.name.substring(0,30):i.sym}</div></div></div></td><td class="qty-cell">${fQ(i.qty)}</td><td class="price-cell">${pd}</td><td class="value-cell">${fU(i.valUSD)}</td>${fc(i.ch24,e)}${fc(i.ch7d,e)}${fc(i.ch30d,e)}${fc(i.ch1y,e)}<td><div class="alloc-bar-wrap"><div class="alloc-bar"><div class="alloc-bar-fill" style="width:${Math.min(al,100)}%"></div></div><span class="alloc-pct">${al.toFixed(1)}%</span></div></td></tr>`;}).join('');}
function sortTable(c){if(curSort.col===c)curSort.dir=curSort.dir==='desc'?'asc':'desc';else{curSort.col=c;curSort.dir='desc';}document.querySelectorAll('.holdings-table th').forEach(t=>t.classList.remove('sort-asc','sort-desc'));const t=document.querySelector(`.holdings-table th[data-col="${c}"]`);if(t)t.classList.add(curSort.dir==='asc'?'sort-asc':'sort-desc');renderH();}

function renderSum(){const it=allItems();const tot=it.reduce((s,i)=>s+i.valUSD,0);const cv=it.filter(i=>i.type==='crypto').reduce((s,i)=>s+i.valUSD,0);const ee=it.filter(i=>i.type==='etf').reduce((s,i)=>s+(i.valEUR||0),0);const eu=it.filter(i=>i.type==='etf').reduce((s,i)=>s+i.valUSD,0);
document.getElementById('totalValue').textContent=fU(tot);document.getElementById('assetCount').textContent=it.filter(i=>i.valUSD>=10).length;
const bk=document.getElementById('breakdown');if(bk)bk.innerHTML=`Crypto: ${fU(cv)} · ETF: €${ee.toFixed(0)} (${fU(eu)})`;
const ci=it.filter(i=>i.type==='crypto'&&i.valUSD>=10);const ct=ci.reduce((s,i)=>s+i.valUSD,0);
if(ct>0){const w=ci.reduce((s,i)=>s+(i.ch24*i.valUSD),0)/ct;const el=document.getElementById('totalChange');el.textContent=`${w>=0?'▲':'▼'} ${w>=0?'+':''}${w.toFixed(2)}% (24h crypto)`;el.className=`total-change ${w>=0?'change-positive':'change-negative'}`;}
// Invested
let inv=0;sbTx.forEach(t=>{if(t.Type==='Deposit'&&['EUR','USD'].includes(t['Asset received'])){const a=pn(t['Amount received']);const cur=t['Asset received'];inv+=cur==='EUR'?a*eurUsd:a;}});
rrTx.forEach(t=>{if((t.Type||'').includes('CASH TOP-UP')){inv+=pn((t['Total Amount']||'').replace(/[^0-9.,]/g,''))*eurUsd;}});
rcTx.forEach(t=>{if((t.Type||'').trim()==='Achat')inv+=pn((t.Value||'').replace(/[^0-9.,]/g,''))*eurUsd;});
document.getElementById('totalInvested').textContent=fU(inv);
const pnl=tot-inv;const pe=document.getElementById('totalPnl');pe.textContent=`${pnl>=0?'+':''}${fU(pnl)}`;pe.className=`summary-card-value ${pnl>=0?'change-positive':'change-negative'}`;
const best=ci.sort((a,b)=>b.ch24-a.ch24)[0];if(best){const el=document.getElementById('bestAsset');el.textContent=`${best.sym} ${best.ch24>=0?'+':''}${best.ch24.toFixed(1)}%`;el.className=`summary-card-value ${best.ch24>=0?'change-positive':'change-negative'}`;}
renderFG();}

function renderFG(){const el=document.getElementById('fearGreed');if(!el||!fgData)return;const v=fgData.value;let c='#ef4444';if(v>75)c='#16a34a';else if(v>55)c='#22c55e';else if(v>45)c='#f59e0b';else if(v>25)c='#f97316';el.innerHTML=`<div style="text-align:center"><div style="font-size:1.8rem;font-weight:700;color:${c};font-family:var(--font-display)">${v}</div><div style="font-size:0.65rem;color:${c};font-family:var(--font-mono);font-weight:600">${fgData.label}</div><div style="width:100%;height:5px;background:var(--bg-secondary);border-radius:3px;margin-top:0.3rem;overflow:hidden"><div style="width:${v}%;height:100%;background:${c};border-radius:3px"></div></div></div>`;}

// Market — with ATH, all periods
function renderMkt(){const g=document.getElementById('marketGrid');if(!mktData.length){g.innerHTML='<div class="loading-cell">Données non disponibles</div>';return;}
const owned=new Set(Object.entries(cryptoH).filter(([s,q])=>q>1e-7).map(([s])=>s.toUpperCase()));
const sorted=[...mktData].sort((a,b)=>{const ao=owned.has(a.symbol.toUpperCase())?0:1,bo=owned.has(b.symbol.toUpperCase())?0:1;if(ao!==bo)return ao-bo;return(a.market_cap_rank||999)-(b.market_cap_rank||999);});
g.innerHTML=sorted.map(c=>{const ch24=c.price_change_percentage_24h||0;const ch7d=c.price_change_percentage_7d_in_currency||0;const ch30d=c.price_change_percentage_30d_in_currency||0;const ch1y=c.price_change_percentage_1y_in_currency||0;const ow=owned.has(c.symbol.toUpperCase());
const athDate=c.ath_date?new Date(c.ath_date).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}):'';
function chSpan(v){const cl=v>=0?'change-positive':'change-negative';return`<span class="${cl}">${v>=0?'+':''}${v.toFixed(1)}%</span>`;}
return`<div class="market-card ${ow?'owned':''}" data-name="${c.name.toLowerCase()} ${c.symbol}">
<div class="market-card-top"><div class="market-card-asset"><div class="asset-icon"><img src="${c.image}" alt="${c.symbol}" onerror="this.parentElement.textContent='${c.symbol.slice(0,2).toUpperCase()}'"></div><div><div class="asset-name">${c.symbol.toUpperCase()}</div><div class="asset-symbol">${c.name}</div></div></div>${ow?'<span class="market-card-owned-badge">DÉTENU</span>':''}<span class="market-card-rank">#${c.market_cap_rank||'--'}</span></div>
<div class="market-card-price">${fU(c.current_price)}</div>
<div class="market-card-changes">
<div class="mc-row"><span class="mc-label">24h</span>${chSpan(ch24)}<span class="mc-label">7j</span>${chSpan(ch7d)}</div>
<div class="mc-row"><span class="mc-label">30j</span>${chSpan(ch30d)}<span class="mc-label">1an</span>${chSpan(ch1y)}</div>
</div>
<div class="market-card-ath"><span class="mc-label">ATH:</span> ${fU(c.ath||0)} <span class="mc-ath-date">${athDate}</span></div>
<div class="market-card-bottom"><span>MCap: ${fC(c.market_cap)}</span></div>
</div>`;}).join('');}

// History
function renderHist(){const list=document.getElementById('historyList');const tf=document.getElementById('historyType').value,af=document.getElementById('historyAsset').value;
let all=[];
sbTx.forEach(t=>{const d=t.Date?new Date(t.Date):null;all.push({date:d,type:t.Type||'',src:'SwissBorg',rq:pn(t['Amount received']),ra:t['Asset received']||'',sq:pn(t['Amount sent']),sa:t['Asset sent']||'',desc:t.Description||''});});
rcTx.forEach(t=>{let d=null;try{const mo={janv:'Jan','févr':'Feb',mars:'Mar',avr:'Apr',mai:'May',juin:'Jun',juil:'Jul','août':'Aug',sept:'Sep',oct:'Oct',nov:'Nov','déc':'Dec'};let s=(t.Date||'');for(const[f,e]of Object.entries(mo))s=s.replace(f+'.',e).replace(f,e);d=new Date(s);if(isNaN(d))d=null;}catch(e){}const tp=(t.Type||'').trim(),sym=(t.Symbol||'').trim(),q=pn(t.Quantity);if(tp==='Achat')all.push({date:d,type:'Trade',src:'Revolut',rq:q,ra:sym,sq:0,sa:'',desc:'Achat'});else if(tp==='Vente')all.push({date:d,type:'Trade',src:'Revolut',rq:0,ra:'',sq:q,sa:sym,desc:'Vente'});else if(tp.includes('compense')||tp.includes('staking'))all.push({date:d,type:'Deposit',src:'Revolut',rq:q,ra:sym,sq:0,sa:'',desc:tp});else if(tp==='Envoi')all.push({date:d,type:'Trade',src:'Revolut',rq:0,ra:'',sq:q,sa:sym,desc:'Envoi'});});
rrTx.forEach(t=>{const d=t.Date?new Date(t.Date):null;const tk=(t.Ticker||'').trim(),tp=(t.Type||'').trim(),q=pn(t.Quantity);if(!tk)return;if(tp.includes('BUY'))all.push({date:d,type:'Trade',src:'Robo',rq:q,ra:tk,sq:0,sa:'',desc:'Achat ETF'});else if(tp.includes('SELL'))all.push({date:d,type:'Trade',src:'Robo',rq:0,ra:'',sq:q,sa:tk,desc:'Vente ETF'});else if(tp.includes('DIVIDEND'))all.push({date:d,type:'Deposit',src:'Robo',rq:0,ra:tk,sq:0,sa:'',desc:'Dividende'});});
let f=all.filter(t=>t.date).sort((a,b)=>b.date-a.date);
if(tf!=='all')f=f.filter(t=>t.type===tf);if(af!=='all')f=f.filter(t=>t.ra===af||t.sa===af);f=f.slice(0,200);
if(!f.length){list.innerHTML='<div class="loading-cell">Aucune transaction</div>';return;}
list.innerHTML=f.map(t=>{const ds=t.date.toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'2-digit'});const ts=t.date.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});const tc=t.type==='Trade'?'trade':'deposit';const sc={SwissBorg:'#06d6a0',Revolut:'#0075eb',Robo:'#ea580c'}[t.src]||'#94a3b8';return`<div class="history-item"><div class="history-date">${ds}<br>${ts}</div><div class="history-type ${tc}">${t.type}</div><div class="history-received">${t.rq?`+${fQ(t.rq)} ${t.ra}`:'—'}</div><div class="history-sent">${t.sq?`-${fQ(t.sq)} ${t.sa}`:'—'}</div><div class="history-desc"><span style="color:${sc};font-size:0.6rem;font-weight:600">${t.src}</span> ${t.desc}</div></div>`;}).join('');}
function popFilter(){const sel=document.getElementById('historyAsset');sel.innerHTML='<option value="all">Tous</option>';const a=new Set();sbTx.forEach(t=>{if(t['Asset received'])a.add(t['Asset received']);if(t['Asset sent'])a.add(t['Asset sent']);});rcTx.forEach(t=>{if(t.Symbol)a.add(t.Symbol);});rrTx.forEach(t=>{if(t.Ticker)a.add(t.Ticker);});[...a].filter(x=>!['EUR','USD'].includes(x)).sort().forEach(x=>{const o=document.createElement('option');o.value=x;o.textContent=x;sel.appendChild(o);});}

// Analytics
function renderAna(){const cv=document.getElementById('allocationChart');cv.width=500;cv.height=400;const ctx=cv.getContext('2d');const it=allItems().filter(i=>i.valUSD>=10).sort((a,b)=>b.valUSD-a.valUSD);const tot=it.reduce((s,i)=>s+i.valUSD,0);if(tot<=0)return;const cols=['#1e3a8a','#2563eb','#3b82f6','#60a5fa','#1d4ed8','#7c3aed','#0891b2','#0d9488','#059669','#d97706','#dc2626','#e11d48'];const cx=cv.width/2,cy=cv.height/2,R=140,iR=R*0.5;ctx.clearRect(0,0,cv.width,cv.height);let sa=-Math.PI/2;const top=it.slice(0,10);const ov=it.slice(10).reduce((s,i)=>s+i.valUSD,0);if(ov>0)top.push({sym:'Autres',valUSD:ov});top.forEach((i,j)=>{const sl=(i.valUSD/tot)*Math.PI*2;ctx.beginPath();ctx.arc(cx,cy,R,sa,sa+sl);ctx.arc(cx,cy,iR,sa+sl,sa,true);ctx.closePath();ctx.fillStyle=cols[j%cols.length];ctx.fill();const p=i.valUSD/tot;if(p>=0.03){const mid=sa+sl/2,lr=(R+iR)/2,lx=cx+Math.cos(mid)*lr,ly=cy+Math.sin(mid)*lr;ctx.save();ctx.fillStyle='#fff';ctx.font='bold 11px "Space Grotesk"';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(i.sym,lx,ly-6);ctx.font='9px "JetBrains Mono"';ctx.fillStyle='rgba(255,255,255,0.8)';ctx.fillText((p*100).toFixed(1)+'%',lx,ly+7);ctx.restore();}sa+=sl;});ctx.fillStyle='#1e293b';ctx.font='bold 18px "Space Grotesk"';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(fU(tot),cx,cy-5);ctx.font='11px "JetBrains Mono"';ctx.fillStyle='#94a3b8';ctx.fillText('TOTAL',cx,cy+12);let leg=cv.parentElement.querySelector('.donut-legend');if(!leg){leg=document.createElement('div');leg.className='donut-legend';cv.parentElement.appendChild(leg);}leg.innerHTML=top.map((i,j)=>`<div class="donut-legend-item"><div class="donut-legend-dot" style="background:${cols[j%cols.length]}"></div>${i.sym} ${fU(i.valUSD)} (${(i.valUSD/tot*100).toFixed(1)}%)</div>`).join('');
// Activity chart
const cv2=document.getElementById('activityChart');const c2=cv2.getContext('2d');c2.clearRect(0,0,cv2.width,cv2.height);const mo={};[...sbTx,...rcTx,...rrTx].forEach(t=>{const d=t.Date?new Date(t.Date):null;if(!d||isNaN(d))return;const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;mo[k]=(mo[k]||0)+1;});const ms=Object.keys(mo).sort().slice(-12);const vs=ms.map(m=>mo[m]);const mx=Math.max(...vs,1);const p=40,w=cv2.width-p*2,h=cv2.height-p*2;const bw=w/ms.length*0.7,gp=w/ms.length*0.3;c2.strokeStyle='#cbd5e1';c2.lineWidth=0.5;for(let i=0;i<=4;i++){const y=p+(h*i/4);c2.beginPath();c2.moveTo(p,y);c2.lineTo(cv2.width-p,y);c2.stroke();}ms.forEach((m,i)=>{const x=p+i*(bw+gp)+gp/2;const bh=(vs[i]/mx)*h,y=p+h-bh;const g=c2.createLinearGradient(x,y,x,p+h);g.addColorStop(0,'#1e3a8a');g.addColorStop(1,'rgba(37,99,235,0.15)');c2.fillStyle=g;c2.beginPath();c2.roundRect(x,y,bw,bh,[3,3,0,0]);c2.fill();c2.fillStyle='#64748b';c2.font='9px "JetBrains Mono"';c2.textAlign='center';c2.fillText(m.slice(5),x+bw/2,p+h+15);c2.fillStyle='#94a3b8';c2.font='10px "JetBrains Mono"';c2.fillText(vs[i],x+bw/2,y-5);});
// Stats
const sg=document.getElementById('statsGrid');sg.innerHTML=[{v:sbTx.filter(t=>t.Type==='Trade').length+rcTx.filter(t=>['Achat','Vente'].includes((t.Type||'').trim())).length,l:'Trades crypto'},{v:rrTx.filter(t=>(t.Type||'').includes('BUY')||(t.Type||'').includes('SELL')).length,l:'Trades ETF'},{v:Object.keys(cryptoH).filter(s=>cryptoH[s]>1e-7).length,l:'Cryptos'},{v:Object.keys(etfH).length,l:'ETFs'},{v:sbTx.length+rcTx.length+rrTx.length,l:'Total opérations'}].map(s=>`<div class="stat-item"><div class="stat-value">${s.v.toLocaleString()}</div><div class="stat-label">${s.l}</div></div>`).join('');}

// Tabs, utils
function switchTab(id){document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));document.querySelector(`[data-tab="${id}"]`).classList.add('active');document.getElementById(`tab-${id}`).classList.add('active');if(id==='analytics')renderAna();if(id==='market'&&!mktData.length)loadMkt();if(id==='evolution')renderEvo();}
function filterMarket(){const q=document.getElementById('marketSearch').value.toLowerCase();document.querySelectorAll('.market-card').forEach(c=>{c.style.display=(c.dataset.name||'').includes(q)?'':'none';});}
function setStatus(t,live){document.querySelector('.status-text').textContent=t;const d=document.querySelector('.status-dot');live?d.classList.add('live'):d.classList.remove('live');}
function updateTime(){document.getElementById('lastUpdate').textContent='Maj: '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});}
function fU(v){if(!v)return'$0';if(Math.abs(v)>=1000)return'$'+v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});if(Math.abs(v)>=1)return'$'+v.toFixed(2);if(Math.abs(v)>=0.01)return'$'+v.toFixed(4);return'$'+v.toFixed(6);}
function fQ(v){if(v>=1e6)return(v/1e6).toFixed(2)+'M';if(v>=1000)return v.toLocaleString('en-US',{maximumFractionDigits:2});if(v>=1)return v.toFixed(4);return v.toFixed(6);}
function fC(v){if(!v)return'--';if(v>=1e12)return'$'+(v/1e12).toFixed(1)+'T';if(v>=1e9)return'$'+(v/1e9).toFixed(1)+'B';if(v>=1e6)return'$'+(v/1e6).toFixed(1)+'M';return'$'+v.toLocaleString();}

// CSV Upload
async function handleUpload(tabName,input){const file=input.files[0];if(!file)return;const statusId=tabName==='Revolut_Crypto'?'statusCrypto':tabName==='Revolut_Robo'?'statusRobo':'statusNeverless';const el=document.getElementById(statusId);el.textContent='⏳ Lecture...';el.className='upload-status uploading';
const text=await file.text();const lines=text.split('\n').filter(l=>l.trim());const csvData=lines.map(l=>csvL(l));
el.textContent=`⏳ Envoi de ${csvData.length} lignes vers Google Sheet...`;
try{const r=await fetch(GAS,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action:'upload_csv',tabName,csvData})});const j=await r.json();if(j.status==='ok'){el.textContent=`✅ ${j.rows} lignes sauvegardées dans "${j.tab}" ! Rechargement...`;el.className='upload-status success';setTimeout(()=>refreshAll(),2000);}else{el.textContent='❌ '+j.message;el.className='upload-status error';}}catch(e){el.textContent='❌ Erreur: '+e.message;el.className='upload-status error';}}

// Evolution
async function logVal(v,n){try{await fetch(GAS,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action:'log_value',valueUSD:v,valueEUR:v/eurUsd,nbAssets:n})});console.log('✓ Value logged');}catch(e){console.warn('Log error:',e.message);}}
async function fetchHist(){try{const r=await fetch(GAS);if(!r.ok)return[];const j=await r.json();if(j.status==='ok'&&j.data)return j.data.map(d=>({date:new Date(d.date),valUSD:d.valueUSD})).sort((a,b)=>a.date-b.date);}catch(e){}return[];}
function selectPeriod(d){selPeriod=d;document.querySelectorAll('.period-btn').forEach(b=>b.classList.remove('active'));document.querySelector(`.period-btn[data-period="${d}"]`)?.classList.add('active');renderEvo();}

function renderEvo(){const cv=document.getElementById('evolutionChart');const ctx=cv.getContext('2d');ctx.clearRect(0,0,cv.width,cv.height);
if(pHistory.length<2){ctx.fillStyle='#94a3b8';ctx.font='14px "DM Sans"';ctx.textAlign='center';ctx.fillText('Pas assez de données. Revenez régulièrement pour remplir le graphique !',cv.width/2,cv.height/2-10);ctx.font='12px "JetBrains Mono"';ctx.fillText(`${pHistory.length} point(s) enregistré(s)`,cv.width/2,cv.height/2+15);document.getElementById('evolutionStats').innerHTML='';return;}
let data=[...pHistory];if(selPeriod>0){const cut=new Date();cut.setDate(cut.getDate()-selPeriod);data=data.filter(d=>d.date>=cut);}if(data.length<2){ctx.fillStyle='#94a3b8';ctx.font='14px "DM Sans"';ctx.textAlign='center';ctx.fillText('Pas assez de données sur cette période.',cv.width/2,cv.height/2);return;}
const pad={t:30,r:30,b:50,l:80};const w=cv.width-pad.l-pad.r,h=cv.height-pad.t-pad.b;const vs=data.map(d=>d.valUSD);const mn=Math.min(...vs)*0.95,mx=Math.max(...vs)*1.05,rn=mx-mn||1;const xS=i=>pad.l+(i/(data.length-1))*w;const yS=v=>pad.t+h-((v-mn)/rn)*h;
ctx.strokeStyle='#e2e8f0';ctx.lineWidth=0.5;for(let i=0;i<=5;i++){const y=pad.t+(h*i/5);const v=mx-(i/5)*rn;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(pad.l+w,y);ctx.stroke();ctx.fillStyle='#94a3b8';ctx.font='10px "JetBrains Mono"';ctx.textAlign='right';ctx.fillText('$'+v.toFixed(0),pad.l-8,y+4);}
const lc=Math.min(data.length,8),sp=Math.max(1,Math.floor(data.length/lc));ctx.fillStyle='#94a3b8';ctx.font='10px "JetBrains Mono"';ctx.textAlign='center';for(let i=0;i<data.length;i+=sp)ctx.fillText(data[i].date.toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit'}),xS(i),pad.t+h+20);
const up=vs[vs.length-1]>=vs[0];const g=ctx.createLinearGradient(0,pad.t,0,pad.t+h);g.addColorStop(0,up?'rgba(30,58,138,0.2)':'rgba(220,38,38,0.15)');g.addColorStop(1,up?'rgba(37,99,235,0.02)':'rgba(220,38,38,0.02)');ctx.beginPath();ctx.moveTo(xS(0),pad.t+h);data.forEach((d,i)=>ctx.lineTo(xS(i),yS(d.valUSD)));ctx.lineTo(xS(data.length-1),pad.t+h);ctx.closePath();ctx.fillStyle=g;ctx.fill();
ctx.beginPath();data.forEach((d,i)=>{const x=xS(i),y=yS(d.valUSD);i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);});ctx.strokeStyle=up?'#1e3a8a':'#dc2626';ctx.lineWidth=2.5;ctx.lineJoin='round';ctx.stroke();
[0,data.length-1].forEach(i=>{const x=xS(i),y=yS(data[i].valUSD);ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fillStyle=up?'#1e3a8a':'#dc2626';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#1e293b';ctx.font='bold 11px "Space Grotesk"';ctx.textAlign=i===0?'left':'right';ctx.fillText('$'+data[i].valUSD.toFixed(0),x+(i===0?10:-10),y-10);});
// Period stats
const c=document.getElementById('evolutionStats');const last=data[data.length-1].valUSD;function findAgo(d){const cut=new Date();cut.setDate(cut.getDate()-d);let cl=null,md=Infinity;pHistory.forEach(p=>{const dd=Math.abs(p.date-cut);if(dd<md){md=dd;cl=p;}});return cl?cl.valUSD:null;}
let html='';[{l:'1j',d:1},{l:'7j',d:7},{l:'30j',d:30},{l:'3m',d:90},{l:'6m',d:180},{l:'1an',d:365},{l:'2ans',d:730},{l:'3ans',d:1095}].forEach(p=>{const pv=findAgo(p.d);if(pv&&pv>0){const ch=((last-pv)/pv)*100;html+=`<div class="evo-stat"><div class="evo-stat-label">${p.l}</div><div class="evo-stat-value ${ch>=0?'change-positive':'change-negative'}">${ch>=0?'+':''}${ch.toFixed(2)}%</div></div>`;}});
const hi=Math.max(...vs),lo=Math.min(...vs),av=vs.reduce((s,v)=>s+v,0)/vs.length;
html+=`<div class="evo-stat"><div class="evo-stat-label">Plus haut</div><div class="evo-stat-value">$${hi.toFixed(0)}</div></div><div class="evo-stat"><div class="evo-stat-label">Plus bas</div><div class="evo-stat-value">$${lo.toFixed(0)}</div></div><div class="evo-stat"><div class="evo-stat-label">Moyenne</div><div class="evo-stat-value">$${av.toFixed(0)}</div></div>`;c.innerHTML=html;}

// Loading
async function loadSheets(){setStatus('Données...');const sb=await getCSV(SB_URLS,'SwissBorg');if(sb)sbTx=parseCSV(sb);const rc=await getCSV(RC_URLS,'Revolut Crypto');if(rc)rcTx=parseCSV(rc);const rr=await getCSV(RR_URLS,'Revolut Robo');if(rr)rrTx=parseCSV(rr);console.log(`SB:${sbTx.length} RC:${rcTx.length} RR:${rrTx.length}`);merge();popFilter();renderHist();return sbTx.length>0;}
async function loadPrices(){setStatus('Prix crypto...');const a=Object.entries(cryptoH).filter(([s,q])=>q>1e-7).map(([s])=>s);prices=await fetchPrices(a);setStatus('Prix ETF...');await fetchETF();renderH();renderSum();setStatus('En direct',true);}
async function loadMkt(){setStatus('Marché...');mktData=await fetchMkt();renderMkt();setStatus('En direct',true);}
async function refreshAll(){const b=document.querySelector('.btn-refresh');b.classList.add('spinning');await loadSheets();await loadPrices();await loadMkt();setStatus('En direct',true);updateTime();b.classList.remove('spinning');}

// Init
async function init(){setStatus('Initialisation...');await Promise.all([fetchFG(),fetchEurUsd()]);const ok=await loadSheets();if(ok){await loadPrices();const it=allItems();const tot=it.reduce((s,i)=>s+i.valUSD,0);const nb=it.filter(i=>i.valUSD>=10).length;if(tot>0)logVal(tot,nb);pHistory=await fetchHist();if(pHistory.length>0)document.getElementById('evolutionStatus').textContent=`${pHistory.length} points · Depuis le ${pHistory[0].date.toLocaleDateString('fr-FR')}`;}setStatus('En direct',true);updateTime();setInterval(async()=>{await loadPrices();updateTime();},60000);}
document.addEventListener('DOMContentLoaded',init);
